version: '2.2'
services:
  grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: infoblox
    restart: always
  loto:
    image: antoj/loto:version1.4
    restart: always
    ports:
      - 22:22
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /home/admins/code:/root/code
    command: /bin/bash -c "service ssh start; mount -a;/bin/bash"
  mysql:
    image: mysql:5.5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: infoblox
      MYSQL_DATABASE: labdb
    restart: always
    tty: true
    stdin_open: true
    privileged: true
    command: /bin/bash -c "docker-entrypoint.sh mysqld; mysql -uroot -pinfoblox -e '[grant all privileges on labdb.* to 'root'@'%' identified by 'infoblox']'"
  testbox:
    image: antoj/loto:version1.4
    restart: always
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /home/admins/code:/root/code
    command: /bin/bash -c "service ssh start; mount -a;/bin/bash" 
  vmdelete:
    image: antoj/loto:version1.4
    restart: always
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /home/admins/code:/root/code
    command: /bin/bash -c "service ssh start; /bin/bash; /root/code/vmdelete" 
